### ISSUE TITLE
mysqli not supported

### ISSUE THREAD

**Issue by Hypser** [purplepixie/freenats#7]
Using the neweste php7, mysql support has been deprecated and replaced with mysqli lib. 

Freenats doesnt support mysqli and there is it doesnt support the neweste php7 version.
The newste ubunto comes with php7 and its a mess to remove and install php5. 

Please include mysqli support :)

**Comment by purplepixie** [comment]
Thank you for your bug report. You are correct in that FreeNATS does use old-style mysql. I will investigate the possibility of using mysqli rather than the old style but this is likely to be a major change.

**Comment by purplepixie** [comment]
Less major than expected! The new alpha release 1.16.0a uses mysqli connections for all user functions (core system and mysql test). I've just run it on our install test boxes and it seems to be working fine, but will of course keep it alpha for a bit.

http://www.purplepixie.org/freenats/release.php?version=1.16.0a

Would be very grateful if you could check this version and see if it works for you.

**Comment by Hypser** [comment]
Hey

I changes the PHP to 5.6 and then i work.

I will try the new alpha release in a few weeks and a new Ubunto release.

Thanks for the update ☺

Med venlig hilsen
Thomas Kristensen
[MM_mail_logo_3_AS]
Storhaven 12 - 7100 Vejle
Tlf: 75 72 54 99 - Fax: 75 72 65 33
E-mail: tk@multimed.dk

Fra: David Cutting [mailto:notifications@github.com]
Sendt: 1. juli 2016 14:37
Til: purplepixie/freenats freenats@noreply.github.com
Cc: Thomas Kristensen TK@multimed.dk; Author author@noreply.github.com
Emne: Re: [purplepixie/freenats] mysqli not supported (#7)

Less major than expected! The new alpha release 1.16.0a uses mysqli connections for all user functions (core system and mysql test). I've just run it on our install test boxes and it seems to be working fine, but will of course keep it alpha for a bit.

http://www.purplepixie.org/freenats/release.php?version=1.16.0a

Would be very grateful if you could check this version and see if it works for you.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHubhttps://github.com/purplepixie/freenats/issues/7#issuecomment-229935881, or mute the threadhttps://github.com/notifications/unsubscribe/AD3nsjvtXMgM8TDE7phkvVp_7fnas139ks5qRQnWgaJpZM4JCGHc.

Denne e-mail kan indeholde fortrolig information. Hvis du ikke er den rette modtager af denne e-mail eller hvis du modtager den ved en fejltagelse, beder vi dig venligst informere afsender om fejlen ved at bruge svarfunktionen. Samtidig bedes du slette e-mailen med det samme uden at videresende eller kopiere den.

**Comment by purplepixie** [comment]
Great many thanks, let me know how you get on. Good luck!

**Comment by purplepixie** [comment]
Hi - did you ever confirm this worked ok at all? Many thanks.

**Comment by purplepixie** [comment]
Validated with PHP7
